Fix problems with go1.7+
bouk/monkey pull request #16
Opened 2018-04-05 23:22 UTC by allenluce

There were failures with go1.7 and higher in the TestOnInstanceMethod test.

First was:

    panic: unknown method no [recovered]
            panic: unknown method no

This appears to be due to https://github.com/golang/go/issues/15673 where unexported methods are made even harder to get to via reflection.

With that addressed, tests still failed:

    --- FAIL: TestOnInstanceMethod (0.00s)
            Error Trace:    monkey_test.go:94
            Error:          Should be true
            Error Trace:    monkey_test.go:95
            Error:          Should be false

This appears to be due to `reflect.Value` no longer being usable to uniquely identify a method. Using `.Pointer()` on the `reflect.Value` gives a workable ID.

2018-04-20 08:54 UTC, allenluce commented
@bouk Are you around to check this out?

2018-04-22 07:55 UTC, artiomgiza commented
@allenluce, cool PR!
Your change should solve issues in `unpatchValue(...)` method: 

The func `unpatchValue(...)` ([link](https://github.com/bouk/monkey/blob/master/monkey.go#L122
)) works wrong. 
To get value from map (with keys of type `reflect.Value`) we should compare `reflect.Value`
But, according to [this](https://github.com/golang/go/commit/a1c9e103719289b4f291fcb631ad324a0e331aed#diff-299545bcc665f75feeed30dce79b50ecR34) it can't be done

2018-07-18 09:32 UTC, adamwen829 commented
Awesome PR！And when will it be merged? @artiomgiza

2018-08-12 08:49 UTC, bouk requested changes

2018-08-12 08:49 UTC, bouk commented on monkey.go
> +  original *reflect.Value
Please run gofmt

2018-09-14 09:58 UTC, bouk commented
Fixed on master!

2018-09-14 09:58 UTC, closed without merging

2018-09-14 16:11 UTC, allenluce commented
Works for me. Also, welcome back.